import React from 'react';
import { motion } from 'framer-motion';
import { Sparkles, BrainCircuit, Activity, HeartPulse } from 'lucide-react';

export default function AnalysisResult({ analysis }) {
  if (!analysis || (!analysis.result && !analysis.summary)) return null;

  return (
    <motion.div
      initial={{ opacity: 0, y: 20 }}
      animate={{ opacity: 1, y: 0 }}
      className="bg-gradient-to-br from-primary-600 to-secondary-600 p-8 sm:p-12 rounded-[3.5rem] text-white shadow-2xl relative overflow-hidden"
    >
      {/* Decorative Orbs */}
      <div className="absolute top-0 right-0 w-64 h-64 bg-white/10 rounded-full blur-3xl -translate-y-1/2 translate-x-1/2"></div>
      <div className="absolute bottom-0 left-0 w-32 h-32 bg-secondary-900/20 rounded-full blur-2xl translate-y-1/2 -translate-x-1/2"></div>

      <div className="relative z-10">
        <div className="flex items-center gap-3 mb-6">
          <div className="bg-white/20 p-3 rounded-2xl backdrop-blur-md">
            <BrainCircuit size={32} />
          </div>
          <h2 className="text-2xl font-black tracking-tight">Your Wellbeing Analysis</h2>
        </div>

        <p className="text-xl sm:text-2xl font-bold leading-relaxed mb-8 text-primary-50">
          "{analysis.summary || analysis.result}"
        </p>

        <div className="grid sm:grid-cols-3 gap-4">
          <div className="bg-white/10 backdrop-blur-md p-4 rounded-[2rem] border border-white/20">
            <Activity className="text-primary-100 mb-2" size={20} />
            <p className="text-xs font-bold text-primary-200">Consistency</p>
            <p className="text-lg font-black italic">{analysis.consistency || "Excellent"}</p>
          </div>
          <div className="bg-white/10 backdrop-blur-md p-4 rounded-[2rem] border border-white/20">
            <HeartPulse className="text-primary-100 mb-2" size={20} />
            <p className="text-xs font-bold text-primary-200">Resilience</p>
            <p className="text-lg font-black italic">{analysis.resilience || "Strong"}</p>
          </div>
          <div className="bg-white/10 backdrop-blur-md p-4 rounded-[2rem] border border-white/20">
            <Sparkles className="text-primary-100 mb-2" size={20} />
            <p className="text-xs font-bold text-primary-200">Mindfulness</p>
            <p className="text-lg font-black italic">{analysis.mindfulness || "Growing"}</p>
          </div>
        </div>

        <div className="mt-10 pt-8 border-t border-white/10 flex flex-col sm:flex-row justify-between items-center gap-4">
          <p className="text-xs text-primary-200 font-medium italic">Generated by Svasthya AI • {new Date(analysis.generatedAt).toLocaleDateString()}</p>
          <button 
            onClick={() => window.print()}
            className="bg-white text-primary-600 px-6 py-2.5 rounded-full text-sm font-black shadow-lg hover:bg-primary-50 transition-colors"
          >
            Download PDF Report
          </button>
        </div>
      </div>
    </motion.div>
  );
}
